IDIR=../inc
SDIR=../src
CXX=g++
CFLAGS=-c -Wall -std=c++20
LFLAGS=-o
SRC=$(SDIR)/message.cpp message-test.cpp
OBJ=message.o message-test.o
EXEC=message-test
INC=-I /usr/include/ -I $(IDIR)
LIB=-lgtest -L /usr/lib64/
RM=rm -rf
BACKUPS=*~

all:
	$(CXX) $(CFLAGS) $(SRC) $(INC)
	$(CXX) $(OBJ) $(LFLAGS) $(EXEC) $(LIB)

clean:
	$(RM) $(OBJ) $(EXEC) $(BACKUPS)
