# select library output and library type according to OS
UNAME_S=$(shell uname -s)
ifeq ($(UNAME_S),Linux)
SHARED=-shared
LIB=lib/libpubsub.so
endif
ifeq ($(UNAME_S),Darwin)
SHARED=-dynamiclib
LIB=lib/libpubsub.dylib
endif
